package alesk.com.masterhelper.domain.docGenerators.consts

const val contractFileName = "contractBEL.docx"
const val estimateFileName = "prices.docx"
const val actFileName = "act.docx"

const val city = "City"
const val actDate = "ActDate"
const val contractNumber = "ContractNumber"
const val contractDate = "ContractDate"
const val jobsDescription = "JobsDescription"
const val projectAddress = "ProjectAddress"

const val materialsSupplier = "MaterialsSupplier"
const val masterSupplier = "подрядчика"
const val clientSupplier = "заказчика"

const val workLength = "WorkLength"
const val workStartDate = "WorkStartDate"
const val workEndDate = "WorkEndDate"

const val prepayment = "Prepayment"
const val prepaymentStartParagaph = "PPS"
const val prepaymentEndParagraph = "PPE"

const val clientName = "ClientName"
const val clientAddress = "ClientAddress"
const val clientPhone = "ClientPhone"
const val clientZip = "ClientZip"
const val clientPassport = "ClientPassport"
const val clientPassportIssued = "ClientPassIssued"
const val clientInsuranceCertificate = "ClientInsuranceCertificate"
const val clientUNP = "ClientUNP"
const val clientBankAccount = "ClientBankAccount"
const val clientBankName = "ClientBankName"
const val clientBankCode = "ClientBankCode"
const val clientBankAddress = "ClientBankAddress"

const val masterName = "MasterName"
const val masterAddress = "MasterAddress"
const val masterPhone = "MasterPhone"
const val masterZip = "MasterZip"
const val masterPassport = "MasterPassport"
const val masterPassportIssued = "MasterPassIssued"
const val masterInsuranceCertificate = "MasterInsuranceCertificate"
const val masterUNP = "MasterUNP"
const val masterBankAccount = "MasterBankAccount"
const val masterBankName = "MasterBankName"
const val masterBankCode = "MasterBankCode"
const val masterBankAddress = "MasterBankAddress"

const val workAcceptanceTerm = "WorkAcceptanceTerm"
const val guaranteeTerm = "GuaranteeTerm"
const val paymentTerm = "PaymentTerm"

const val estimateSum = "EstimateSum"
const val estimateDate = "EstimateDate"